<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net48</TargetFrameworks>
    <RootNamespace>SigmaStudio.Graph</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SigmaStudio.Contracts\SigmaStudio.Contracts.csproj" />
  </ItemGroup>
</Project>
